version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: fastapi.Dockerfile
    image: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend/main.py:/code/main.py
      - ./backend/models.py:/code/models.py
      - ./backend/scheduAlgoClasses.py:/code/scheduAlgoClasses.py
      - ./backend/algorithm.py:/code/algorithm.py
    environment:
      - FASTPI_DEBUG=true
      - FASTPI_SECRET=supersecret
      - FASTPI_TITLE=FastAPI
      - FASTPI_VERSION=3.9
      - USER=${CURRENT_UID}
    restart: "no"

  vue:
    build:
      context: .
      dockerfile: vue.Dockerfile
    image: react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/usr/src/app/
    restart: "no"
    depends_on:
      - fastapi
